# Generated by Django 4.1.1 on 2022-09-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_facebook_alter_user_instagram_and_more'),
        ('Front', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('Authentication.repeatfields',),
        ),
    ]
