# Generated by Django 4.1.1 on 2022-09-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPropertyImage',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('image1', models.ImageField(upload_to='Additional_Images')),
                ('image2', models.ImageField(upload_to='Additional_Images')),
                ('image3', models.ImageField(upload_to='Additional_Images')),
                ('image4', models.ImageField(upload_to='Additional_Images')),
                ('image5', models.ImageField(upload_to='Additional_Images')),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bathrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('country', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Garages',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('type', models.CharField(choices=[('FOR SALE', 'For Sale'), ('FOR RENT', 'For Rent')], max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('inactiverepeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.inactiverepeatfields')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('address_name', models.CharField(max_length=150)),
                ('main_image', models.ImageField(upload_to='Property_images')),
                ('bathroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_bathrooms', to='Property.bathrooms')),
                ('bedroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_bedrooms', to='Property.bedrooms')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_country', to='Property.countries')),
                ('garage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_garages', to='Property.garages')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_property_type', to='Property.propertytypes')),
            ],
            bases=('Authentication.inactiverepeatfields',),
        ),
    ]
