# Generated by Django 4.1.1 on 2022-09-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPropertyImage',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('image1', models.ImageField(upload_to='Additional_Images')),
                ('image2', models.ImageField(upload_to='Additional_Images')),
                ('image3', models.ImageField(upload_to='Additional_Images')),
                ('image4', models.ImageField(upload_to='Additional_Images')),
                ('image5', models.ImageField(upload_to='Additional_Images')),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bathrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Bedrooms',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('number', models.CharField(max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('property_types', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('OFFICE', 'Office')], max_length=150)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('repeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields')),
                ('state', models.CharField(choices=[('FOR RENT', 'For Rent'), ('FOR SALE', 'For Sale')], max_length=254)),
            ],
            bases=('Authentication.repeatfields',),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('inactiverepeatfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.inactiverepeatfields')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=150)),
                ('garage', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Property_images')),
                ('additional_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Property.additionalpropertyimage')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_city', to='Authentication.cities')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_country', to='Authentication.country')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_type', to='Property.propertytype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_status', to='Property.status')),
            ],
            bases=('Authentication.inactiverepeatfields',),
        ),
    ]
