# Generated by Django 4.1.1 on 2022-09-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0001_initial'),
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='inactiverepeatfields_ptr',
        ),
        migrations.AddField(
            model_name='properties',
            name='repeatfields_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.repeatfields'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
